### PR TITLE
Add Ref: non-nullable Ptr

### PR DESCRIPTION
**Pull request by jeehoonkang**
For e.g., `store_box` returns a Ptr that should not be null.  This
commit introduces a new type, `Ref`, non-nullable Ptr, to express
this idea in the type.

### CODE REVIEW

**Comment by jeehoonkang** [comment]
Hi @stjepang !  Today I am studying coco, and got several questions.  I will ask (by filing an issue or making a PR) one by one.  This is my first PR, which is on the type `Ptr<T>`.

In terms of Crossbeam, `Ptr<T>` ~= `Option<Shared<T>>`, while `Ref<T>` ~= `Shared<T>`, while you can tag a null pointer in coco.

I guess you didn't go for `Option<Ref<T>>` is that (1) it will be 16 bytes long (in 64 bit archs), while ideally a reference/pointer should be 8 bytes long; and (2) `option` is not ergonomic.  I agree with (1), and for (2) I don't.  In my opinion, `Option`s should be type-inferred for most of the time, and in that case the API will not be tiresome.

I would to ask your opinion.

**Comment by stjepang** [comment]
Hey! :) Thank you for looking into the code and your kind words!

> and for (2) I don't: in my opinion, `Option`s should be type-inferred for most of the time, and in that case the API will not be tiresome.

True, if `Option`s are returned from functions, they can be type-inferred and don't present any difficulties. However, if `Option`s must be passed as argument to functions, then I sometimes find them clunky to use.

Before settling with the current API, I in fact had a very crossbeam-like API with `Option`s everywhere, and that felt uncomfortable while I was implementing a skiplist. Queues and stacks were no problem, but skiplists were painful.

I tend to agree with you in the sense that tightening types and making them as specific as possible is good and leads to more robust code. I like this PR and it seems like the way to go, but would like to do a case study first...

My suggestion is that we keep the API as-is for now (simple and uniform) and wait until the skiplist is fully implemented and merged into this repository. Then we adapt the skiplist to this PR and see how it affects robustness and ergonomics. What do you think?

**Comment by jeehoonkang** [comment]
Sure!  As you said, we need more  case studies.  Let's wait for things to get sorted out.

**Comment by stjepang** [comment]
We've discussed this in the crossbeam-rfcs project. Closing.

**Pull request closed without merging**
